{
 "title": "Spring Petclinic Metrics",
 "time": { "from": "2025-06-17T12:46:52.633Z", "to": "2025-06-17T14:46:52.633Z" },
 "templating": {
  "list": [
   {
    "name": "timeRange",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Request in 24h",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count[24h])) OR vector(0)"
    }
   ]
  },
  {
   "title": "Success (2xx)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{status=~\"2..\"}[24h])) OR vector(0)"
    }
   ]
  },
  {
   "title": "Error (5xx)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{status=~\"5..\"}[24h])) OR vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total HTTP Response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{status=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{status=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  }
 ]
}